<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('countries')->delete();
        
        \DB::table('countries')->insert(array (
            0 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 1,
                'name' => 'Afghanistan',
                'status' => 1,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 2,
            'name' => 'Åland (Finland)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 3,
                'name' => 'Albania',
                'status' => 1,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 4,
                'name' => 'Algeria',
                'status' => 1,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 5,
            'name' => 'American Samoa (US)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 6,
                'name' => 'Andorra',
                'status' => 1,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 7,
                'name' => 'Angola',
                'status' => 1,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 8,
            'name' => 'Anguilla (BOT)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 9,
                'name' => 'Antigua and Barbuda',
                'status' => 1,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 10,
                'name' => 'Argentina',
                'status' => 1,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 11,
                'name' => 'Armenia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 12,
                'name' => 'Artsakh',
                'status' => 1,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 13,
            'name' => 'Aruba (Netherlands)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 14,
                'name' => 'Australia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 15,
                'name' => 'Austria',
                'status' => 1,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 16,
                'name' => 'Azerbaijan',
                'status' => 1,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 17,
                'name' => 'Bahamas',
                'status' => 1,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 18,
                'name' => 'Bahrain',
                'status' => 1,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'created_at' => NULL,
                'currency_name' => 'BDT',
                'deleted_at' => NULL,
                'dollar_rate' => 109.78,
                'id' => 19,
                'name' => 'Bangladesh',
                'status' => 1,
                'updated_at' => '2024-03-17 00:02:38',
            ),
            19 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 20,
                'name' => 'Barbados',
                'status' => 1,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 21,
                'name' => 'Belarus',
                'status' => 1,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 22,
                'name' => 'Belgium',
                'status' => 1,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 23,
                'name' => 'Belize',
                'status' => 1,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 24,
                'name' => 'Benin',
                'status' => 1,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 25,
            'name' => 'Bermuda (BOT)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 26,
                'name' => 'Bhutan',
                'status' => 1,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 27,
                'name' => 'Bolivia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 28,
            'name' => 'Bonaire (Netherlands)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 29,
                'name' => 'Bosnia and Herzegovina',
                'status' => 1,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 30,
                'name' => 'Botswana',
                'status' => 1,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 31,
                'name' => 'Brazil',
                'status' => 1,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 32,
            'name' => 'British Virgin Islands (BOT)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 33,
                'name' => 'Brunei',
                'status' => 1,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 34,
                'name' => 'Bulgaria',
                'status' => 1,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 35,
                'name' => 'Burkina Faso',
                'status' => 1,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 36,
                'name' => 'Burundi',
                'status' => 1,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 37,
                'name' => 'Cambodia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 38,
                'name' => 'Cameroon',
                'status' => 1,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 39,
                'name' => 'Canada',
                'status' => 1,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 40,
                'name' => 'Cape Verde',
                'status' => 1,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 41,
            'name' => 'Cayman Islands (BOT)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 42,
                'name' => 'Central African Republic',
                'status' => 1,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 43,
                'name' => 'Chad',
                'status' => 1,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 44,
                'name' => 'Chile',
                'status' => 1,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 45,
                'name' => 'China',
                'status' => 1,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 46,
            'name' => 'Christmas Island (Australia)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 47,
            'name' => 'Cocos (Keeling) Islands (Australia)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 48,
                'name' => 'Colombia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 49,
                'name' => 'Comoros',
                'status' => 1,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 50,
                'name' => 'Congo',
                'status' => 1,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 51,
                'name' => 'Cook Islands',
                'status' => 1,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 52,
                'name' => 'Costa Rica',
                'status' => 1,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 53,
                'name' => 'Croatia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 54,
                'name' => 'Cuba',
                'status' => 1,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 55,
            'name' => 'Curaçao (Netherlands)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 56,
                'name' => 'Cyprus',
                'status' => 1,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 57,
                'name' => 'Czech Republic',
                'status' => 1,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 58,
                'name' => 'Denmark',
                'status' => 1,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 59,
                'name' => 'Djibouti',
                'status' => 1,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 60,
                'name' => 'Dominica',
                'status' => 1,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 61,
                'name' => 'Dominican Republic',
                'status' => 1,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 62,
                'name' => 'DR Congo',
                'status' => 1,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 63,
                'name' => 'East Timor',
                'status' => 1,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 64,
                'name' => 'Ecuador',
                'status' => 1,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 65,
                'name' => 'Egypt',
                'status' => 1,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 66,
                'name' => 'El Salvador',
                'status' => 1,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 67,
                'name' => 'Equatorial Guinea',
                'status' => 1,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 68,
                'name' => 'Eritrea',
                'status' => 1,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 69,
                'name' => 'Estonia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 70,
                'name' => 'Eswatini',
                'status' => 1,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 71,
                'name' => 'Ethiopia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 72,
            'name' => 'Falkland Islands (BOT)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 73,
            'name' => 'Faroe Islands (Denmark)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 74,
                'name' => 'Fiji',
                'status' => 1,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 75,
                'name' => 'Finland',
                'status' => 1,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 76,
                'name' => 'France',
                'status' => 1,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 77,
            'name' => 'French Guiana (France)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 78,
            'name' => 'French Polynesia (France)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 79,
                'name' => 'Gabon',
                'status' => 1,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 80,
                'name' => 'Gambia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 81,
                'name' => 'Georgia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 82,
                'name' => 'Germany',
                'status' => 1,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 83,
                'name' => 'Ghana',
                'status' => 1,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 84,
            'name' => 'Gibraltar (BOT)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 85,
                'name' => 'Greece',
                'status' => 1,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 86,
            'name' => 'Greenland (Denmark)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 87,
                'name' => 'Grenada',
                'status' => 1,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 88,
            'name' => 'Guadeloupe (France)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 89,
            'name' => 'Guam (US)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 90,
                'name' => 'Guatemala',
                'status' => 1,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 91,
            'name' => 'Guernsey (Crown Dependency)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 92,
                'name' => 'Guinea',
                'status' => 1,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 93,
                'name' => 'Guinea-Bissau',
                'status' => 1,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 94,
                'name' => 'Guyana',
                'status' => 1,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 95,
                'name' => 'Haiti',
                'status' => 1,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 96,
                'name' => 'Honduras',
                'status' => 1,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 97,
                'name' => 'Hong Kong',
                'status' => 1,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 98,
                'name' => 'Hungary',
                'status' => 1,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 99,
                'name' => 'Iceland',
                'status' => 1,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'created_at' => NULL,
                'currency_name' => 'INR',
                'deleted_at' => NULL,
                'dollar_rate' => 82.89,
                'id' => 100,
                'name' => 'India',
                'status' => 1,
                'updated_at' => '2024-03-17 00:04:43',
            ),
            100 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 101,
                'name' => 'Indonesia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 102,
                'name' => 'Iran',
                'status' => 1,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 103,
                'name' => 'Iraq',
                'status' => 1,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 104,
                'name' => 'Ireland',
                'status' => 1,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 105,
            'name' => 'Isle of Man (Crown Dependency)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 106,
                'name' => 'Israel',
                'status' => 1,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 107,
                'name' => 'Italy',
                'status' => 1,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 108,
                'name' => 'Ivory Coast',
                'status' => 1,
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 109,
                'name' => 'Jamaica',
                'status' => 1,
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 110,
                'name' => 'Japan',
                'status' => 1,
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 111,
            'name' => 'Jersey (Crown Dependency)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 112,
                'name' => 'Jordan',
                'status' => 1,
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 113,
                'name' => 'Kazakhstan',
                'status' => 1,
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 114,
                'name' => 'Kenya',
                'status' => 1,
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 115,
                'name' => 'Kiribati',
                'status' => 1,
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 116,
                'name' => 'Kosovo',
                'status' => 1,
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'created_at' => NULL,
                'currency_name' => 'KWD',
                'deleted_at' => NULL,
                'dollar_rate' => 0.31,
                'id' => 117,
                'name' => 'Kuwait',
                'status' => 1,
                'updated_at' => '2024-03-17 00:05:30',
            ),
            117 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 118,
                'name' => 'Kyrgyzstan',
                'status' => 1,
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 119,
                'name' => 'Laos',
                'status' => 1,
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 120,
                'name' => 'Latvia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 121,
                'name' => 'Lebanon',
                'status' => 1,
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 122,
                'name' => 'Lesotho',
                'status' => 1,
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 123,
                'name' => 'Liberia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 124,
                'name' => 'Libya',
                'status' => 1,
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 125,
                'name' => 'Liechtenstein',
                'status' => 1,
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 126,
                'name' => 'Lithuania',
                'status' => 1,
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 127,
                'name' => 'Luxembourg',
                'status' => 1,
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 128,
                'name' => 'Macau',
                'status' => 1,
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 129,
                'name' => 'Madagascar',
                'status' => 1,
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 130,
                'name' => 'Malawi',
                'status' => 1,
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 131,
                'name' => 'Malaysia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 132,
                'name' => 'Maldives',
                'status' => 1,
                'updated_at' => NULL,
            ),
            132 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 133,
                'name' => 'Mali',
                'status' => 1,
                'updated_at' => NULL,
            ),
            133 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 134,
                'name' => 'Malta',
                'status' => 1,
                'updated_at' => NULL,
            ),
            134 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 135,
                'name' => 'Marshall Islands',
                'status' => 1,
                'updated_at' => NULL,
            ),
            135 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 136,
            'name' => 'Martinique (France)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            136 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 137,
                'name' => 'Mauritania',
                'status' => 1,
                'updated_at' => NULL,
            ),
            137 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 138,
                'name' => 'Mauritius',
                'status' => 1,
                'updated_at' => NULL,
            ),
            138 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 139,
            'name' => 'Mayotte (France)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            139 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 140,
                'name' => 'Mexico',
                'status' => 1,
                'updated_at' => NULL,
            ),
            140 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 141,
                'name' => 'Micronesia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            141 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 142,
                'name' => 'Moldova',
                'status' => 1,
                'updated_at' => NULL,
            ),
            142 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 143,
                'name' => 'Monaco',
                'status' => 1,
                'updated_at' => NULL,
            ),
            143 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 144,
                'name' => 'Mongolia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            144 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 145,
                'name' => 'Montenegro',
                'status' => 1,
                'updated_at' => NULL,
            ),
            145 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 146,
            'name' => 'Montserrat (BOT)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            146 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 147,
                'name' => 'Morocco',
                'status' => 1,
                'updated_at' => NULL,
            ),
            147 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 148,
                'name' => 'Mozambique',
                'status' => 1,
                'updated_at' => NULL,
            ),
            148 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 149,
                'name' => 'Myanmar',
                'status' => 1,
                'updated_at' => NULL,
            ),
            149 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 150,
                'name' => 'Namibia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            150 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 151,
                'name' => 'Nauru',
                'status' => 1,
                'updated_at' => NULL,
            ),
            151 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 152,
                'name' => 'Nepal',
                'status' => 1,
                'updated_at' => NULL,
            ),
            152 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 153,
                'name' => 'Netherlands',
                'status' => 1,
                'updated_at' => NULL,
            ),
            153 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 154,
            'name' => 'New Caledonia (France)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            154 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 155,
                'name' => 'New Zealand',
                'status' => 1,
                'updated_at' => NULL,
            ),
            155 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 156,
                'name' => 'Nicaragua',
                'status' => 1,
                'updated_at' => NULL,
            ),
            156 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 157,
                'name' => 'Niger',
                'status' => 1,
                'updated_at' => NULL,
            ),
            157 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 158,
                'name' => 'Nigeria',
                'status' => 1,
                'updated_at' => NULL,
            ),
            158 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 159,
                'name' => 'Niue',
                'status' => 1,
                'updated_at' => NULL,
            ),
            159 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 160,
            'name' => 'Norfolk Island (Australia)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            160 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 161,
                'name' => 'North Korea',
                'status' => 1,
                'updated_at' => NULL,
            ),
            161 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 162,
                'name' => 'North Macedonia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            162 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 163,
                'name' => 'Northern Cyprus',
                'status' => 1,
                'updated_at' => NULL,
            ),
            163 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 164,
            'name' => 'Northern Mariana Islands (US)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            164 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 165,
                'name' => 'Norway',
                'status' => 1,
                'updated_at' => NULL,
            ),
            165 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 166,
                'name' => 'Oman',
                'status' => 1,
                'updated_at' => NULL,
            ),
            166 => 
            array (
                'created_at' => NULL,
                'currency_name' => 'PKR',
                'deleted_at' => NULL,
                'dollar_rate' => 279.48,
                'id' => 167,
                'name' => 'Pakistan',
                'status' => 1,
                'updated_at' => '2024-03-17 00:07:10',
            ),
            167 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 168,
                'name' => 'Palau',
                'status' => 1,
                'updated_at' => NULL,
            ),
            168 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 169,
                'name' => 'Palestine',
                'status' => 1,
                'updated_at' => NULL,
            ),
            169 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 170,
                'name' => 'Panama',
                'status' => 1,
                'updated_at' => NULL,
            ),
            170 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 171,
                'name' => 'Papua New Guinea',
                'status' => 1,
                'updated_at' => NULL,
            ),
            171 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 172,
                'name' => 'Paraguay',
                'status' => 1,
                'updated_at' => NULL,
            ),
            172 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 173,
                'name' => 'Peru',
                'status' => 1,
                'updated_at' => NULL,
            ),
            173 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 174,
                'name' => 'Philippines',
                'status' => 1,
                'updated_at' => NULL,
            ),
            174 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 175,
            'name' => 'Pitcairn Islands (BOT)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            175 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 176,
                'name' => 'Poland',
                'status' => 1,
                'updated_at' => NULL,
            ),
            176 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 177,
                'name' => 'Portugal',
                'status' => 1,
                'updated_at' => NULL,
            ),
            177 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 178,
            'name' => 'Puerto Rico (US)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            178 => 
            array (
                'created_at' => NULL,
                'currency_name' => 'QAR',
                'deleted_at' => NULL,
                'dollar_rate' => 3.64,
                'id' => 179,
                'name' => 'Qatar',
                'status' => 1,
                'updated_at' => '2024-03-17 00:06:22',
            ),
            179 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 180,
            'name' => 'Réunion (France)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            180 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 181,
                'name' => 'Romania',
                'status' => 1,
                'updated_at' => NULL,
            ),
            181 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 182,
                'name' => 'Russia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            182 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 183,
                'name' => 'Rwanda',
                'status' => 1,
                'updated_at' => NULL,
            ),
            183 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 184,
            'name' => 'Saba (Netherlands)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            184 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 185,
            'name' => 'Saint Barthélemy (France)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            185 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 186,
            'name' => 'Saint Helena, Ascension and Tristan da Cunha (BOT)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            186 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 187,
                'name' => 'Saint Kitts and Nevis',
                'status' => 1,
                'updated_at' => NULL,
            ),
            187 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 188,
                'name' => 'Saint Lucia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            188 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 189,
            'name' => 'Saint Martin (France)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            189 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 190,
            'name' => 'Saint Pierre and Miquelon (France)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            190 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 191,
                'name' => 'Saint Vincent and the Grenadines',
                'status' => 1,
                'updated_at' => NULL,
            ),
            191 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 192,
                'name' => 'Samoa',
                'status' => 1,
                'updated_at' => NULL,
            ),
            192 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 193,
                'name' => 'San Marino',
                'status' => 1,
                'updated_at' => NULL,
            ),
            193 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 194,
                'name' => 'São Tomé and Príncipe',
                'status' => 1,
                'updated_at' => NULL,
            ),
            194 => 
            array (
                'created_at' => NULL,
                'currency_name' => 'SAR',
                'deleted_at' => NULL,
                'dollar_rate' => 3.75,
                'id' => 195,
                'name' => 'Saudi Arabia',
                'status' => 1,
                'updated_at' => '2024-03-17 00:04:01',
            ),
            195 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 196,
                'name' => 'Senegal',
                'status' => 1,
                'updated_at' => NULL,
            ),
            196 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 197,
                'name' => 'Serbia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            197 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 198,
                'name' => 'Seychelles',
                'status' => 1,
                'updated_at' => NULL,
            ),
            198 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 199,
                'name' => 'Sierra Leone',
                'status' => 1,
                'updated_at' => NULL,
            ),
            199 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 200,
                'name' => 'Singapore',
                'status' => 1,
                'updated_at' => NULL,
            ),
            200 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 201,
            'name' => 'Sint Eustatius (Netherlands)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            201 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 202,
            'name' => 'Sint Maarten (Netherlands)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            202 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 203,
                'name' => 'Slovakia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            203 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 204,
                'name' => 'Slovenia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            204 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 205,
                'name' => 'Solomon Islands',
                'status' => 1,
                'updated_at' => NULL,
            ),
            205 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 206,
                'name' => 'Somalia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            206 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 207,
                'name' => 'South Africa',
                'status' => 1,
                'updated_at' => NULL,
            ),
            207 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 208,
                'name' => 'South Korea',
                'status' => 1,
                'updated_at' => NULL,
            ),
            208 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 209,
                'name' => 'South Sudan',
                'status' => 1,
                'updated_at' => NULL,
            ),
            209 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 210,
                'name' => 'Spain',
                'status' => 1,
                'updated_at' => NULL,
            ),
            210 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 211,
                'name' => 'Sri Lanka',
                'status' => 1,
                'updated_at' => NULL,
            ),
            211 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 212,
                'name' => 'Sudan',
                'status' => 1,
                'updated_at' => NULL,
            ),
            212 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 213,
                'name' => 'Suriname',
                'status' => 1,
                'updated_at' => NULL,
            ),
            213 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 214,
            'name' => 'Svalbard and Jan Mayen (Norway)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            214 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 215,
                'name' => 'Sweden',
                'status' => 1,
                'updated_at' => NULL,
            ),
            215 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 216,
                'name' => 'Switzerland',
                'status' => 1,
                'updated_at' => NULL,
            ),
            216 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 217,
                'name' => 'Syria',
                'status' => 1,
                'updated_at' => NULL,
            ),
            217 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 218,
                'name' => 'Taiwan',
                'status' => 1,
                'updated_at' => NULL,
            ),
            218 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 219,
                'name' => 'Tajikistan',
                'status' => 1,
                'updated_at' => NULL,
            ),
            219 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 220,
                'name' => 'Tanzania',
                'status' => 1,
                'updated_at' => NULL,
            ),
            220 => 
            array (
                'created_at' => NULL,
                'currency_name' => 'THB',
                'deleted_at' => NULL,
                'dollar_rate' => 35.85,
                'id' => 221,
                'name' => 'Thailand',
                'status' => 1,
                'updated_at' => '2024-03-17 00:03:13',
            ),
            221 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 222,
                'name' => 'Togo',
                'status' => 1,
                'updated_at' => NULL,
            ),
            222 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 223,
            'name' => 'Tokelau (NZ)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            223 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 224,
                'name' => 'Tonga',
                'status' => 1,
                'updated_at' => NULL,
            ),
            224 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 225,
                'name' => 'Transnistria',
                'status' => 1,
                'updated_at' => NULL,
            ),
            225 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 226,
                'name' => 'Trinidad and Tobago',
                'status' => 1,
                'updated_at' => NULL,
            ),
            226 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 227,
                'name' => 'Tunisia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            227 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 228,
                'name' => 'Turkey',
                'status' => 1,
                'updated_at' => NULL,
            ),
            228 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 229,
                'name' => 'Turkmenistan',
                'status' => 1,
                'updated_at' => NULL,
            ),
            229 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 230,
            'name' => 'Turks and Caicos Islands (BOT)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            230 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 231,
                'name' => 'Tuvalu',
                'status' => 1,
                'updated_at' => NULL,
            ),
            231 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 232,
            'name' => 'U.S. Virgin Islands (US)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            232 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 233,
                'name' => 'Uganda',
                'status' => 1,
                'updated_at' => NULL,
            ),
            233 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 234,
                'name' => 'Ukraine',
                'status' => 1,
                'updated_at' => NULL,
            ),
            234 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 235,
                'name' => 'United Arab Emirates',
                'status' => 1,
                'updated_at' => NULL,
            ),
            235 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 236,
                'name' => 'United Kingdom',
                'status' => 1,
                'updated_at' => NULL,
            ),
            236 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 237,
                'name' => 'United States',
                'status' => 1,
                'updated_at' => NULL,
            ),
            237 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 238,
                'name' => 'Uruguay',
                'status' => 1,
                'updated_at' => NULL,
            ),
            238 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 239,
                'name' => 'Uzbekistan',
                'status' => 1,
                'updated_at' => NULL,
            ),
            239 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 240,
                'name' => 'Vanuatu',
                'status' => 1,
                'updated_at' => NULL,
            ),
            240 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 241,
                'name' => 'Vatican City',
                'status' => 1,
                'updated_at' => NULL,
            ),
            241 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 242,
                'name' => 'Venezuela',
                'status' => 1,
                'updated_at' => NULL,
            ),
            242 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 243,
                'name' => 'Vietnam',
                'status' => 1,
                'updated_at' => NULL,
            ),
            243 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 244,
            'name' => 'Wallis and Futuna (France)',
                'status' => 1,
                'updated_at' => NULL,
            ),
            244 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 245,
                'name' => 'Western Sahara',
                'status' => 1,
                'updated_at' => NULL,
            ),
            245 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 246,
                'name' => 'Yemen',
                'status' => 1,
                'updated_at' => NULL,
            ),
            246 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 247,
                'name' => 'Zambia',
                'status' => 1,
                'updated_at' => NULL,
            ),
            247 => 
            array (
                'created_at' => NULL,
                'currency_name' => NULL,
                'deleted_at' => NULL,
                'dollar_rate' => NULL,
                'id' => 248,
                'name' => 'Zimbabwe',
                'status' => 1,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}