<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CustomerTransactionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('customer_transactions')->delete();
        
        \DB::table('customer_transactions')->insert(array (
            0 => 
            array (
                'approved_by' => 1,
                'balance' => 100.0,
                'created_at' => '2024-02-14 13:20:21',
                'date' => '2024-02-14',
                'deleted_at' => NULL,
                'document' => NULL,
                'expense' => NULL,
                'id' => 1,
                'member_id' => 'M-000001',
                'payment_account' => NULL,
                'payment_type' => NULL,
                'status' => 1,
                'time' => '13:20:21',
                'transaction_id' => NULL,
                'transaction_type' => 1,
                'transfer' => NULL,
                'transfer_from' => NULL,
                'transfer_to' => NULL,
                'updated_at' => '2024-02-14 13:20:21',
                'vat' => NULL,
                'winbalance' => NULL,
                'winbalance_transfer' => NULL,
                'withdraw' => NULL,
            ),
            1 => 
            array (
                'approved_by' => 1,
                'balance' => NULL,
                'created_at' => '2024-02-14 13:20:30',
                'date' => '2024-02-14',
                'deleted_at' => NULL,
                'document' => NULL,
                'expense' => NULL,
                'id' => 2,
                'member_id' => 'M-000001',
                'payment_account' => NULL,
                'payment_type' => NULL,
                'status' => 1,
                'time' => '13:20:30',
                'transaction_id' => NULL,
                'transaction_type' => 5,
                'transfer' => NULL,
                'transfer_from' => NULL,
                'transfer_to' => NULL,
                'updated_at' => '2024-02-14 13:20:30',
                'vat' => NULL,
                'winbalance' => 100.0,
                'winbalance_transfer' => NULL,
                'withdraw' => NULL,
            ),
            2 => 
            array (
                'approved_by' => NULL,
                'balance' => -5.05,
                'created_at' => '2024-02-14 13:20:53',
                'date' => '2024-02-14',
                'deleted_at' => NULL,
                'document' => NULL,
                'expense' => NULL,
                'id' => 3,
                'member_id' => 'M-000001',
                'payment_account' => NULL,
                'payment_type' => NULL,
                'status' => 1,
                'time' => '13:20:53',
                'transaction_id' => NULL,
                'transaction_type' => 6,
                'transfer' => NULL,
                'transfer_from' => NULL,
                'transfer_to' => NULL,
                'updated_at' => '2024-02-14 13:20:53',
                'vat' => 0.05,
                'winbalance' => 5.0,
                'winbalance_transfer' => NULL,
                'withdraw' => NULL,
            ),
            3 => 
            array (
                'approved_by' => NULL,
                'balance' => 2.0,
                'created_at' => '2024-02-14 13:21:22',
                'date' => '2024-02-14',
                'deleted_at' => NULL,
                'document' => NULL,
                'expense' => NULL,
                'id' => 4,
                'member_id' => 'M-000001',
                'payment_account' => NULL,
                'payment_type' => NULL,
                'status' => 1,
                'time' => '13:21:22',
                'transaction_id' => NULL,
                'transaction_type' => 7,
                'transfer' => NULL,
                'transfer_from' => NULL,
                'transfer_to' => NULL,
                'updated_at' => '2024-02-14 13:21:22',
                'vat' => 0.02,
                'winbalance' => -2.02,
                'winbalance_transfer' => NULL,
                'withdraw' => NULL,
            ),
            4 => 
            array (
                'approved_by' => NULL,
                'balance' => NULL,
                'created_at' => '2024-02-14 13:24:15',
                'date' => '2024-02-14',
                'deleted_at' => NULL,
                'document' => NULL,
                'expense' => NULL,
                'id' => 5,
                'member_id' => 'M-000001',
                'payment_account' => NULL,
                'payment_type' => NULL,
                'status' => 1,
                'time' => '13:24:15',
                'transaction_id' => NULL,
                'transaction_type' => 2,
                'transfer' => 10.3,
                'transfer_from' => NULL,
                'transfer_to' => 'M-000002',
                'updated_at' => '2024-02-14 13:24:15',
                'vat' => 0.3,
                'winbalance' => NULL,
                'winbalance_transfer' => NULL,
                'withdraw' => NULL,
            ),
            5 => 
            array (
                'approved_by' => NULL,
                'balance' => 10.0,
                'created_at' => '2024-02-14 13:24:15',
                'date' => '2024-02-14',
                'deleted_at' => NULL,
                'document' => NULL,
                'expense' => NULL,
                'id' => 6,
                'member_id' => 'M-000002',
                'payment_account' => NULL,
                'payment_type' => NULL,
                'status' => 1,
                'time' => '13:24:15',
                'transaction_id' => NULL,
                'transaction_type' => 2,
                'transfer' => NULL,
                'transfer_from' => 'M-000001',
                'transfer_to' => NULL,
                'updated_at' => '2024-02-14 13:24:15',
                'vat' => NULL,
                'winbalance' => NULL,
                'winbalance_transfer' => NULL,
                'withdraw' => NULL,
            ),
            6 => 
            array (
                'approved_by' => NULL,
                'balance' => NULL,
                'created_at' => '2024-02-14 13:24:43',
                'date' => '2024-02-14',
                'deleted_at' => NULL,
                'document' => NULL,
                'expense' => NULL,
                'id' => 7,
                'member_id' => 'M-000001',
                'payment_account' => NULL,
                'payment_type' => NULL,
                'status' => 1,
                'time' => '13:24:43',
                'transaction_id' => NULL,
                'transaction_type' => 8,
                'transfer' => NULL,
                'transfer_from' => NULL,
                'transfer_to' => 'M-000003',
                'updated_at' => '2024-02-14 13:24:43',
                'vat' => 0.1,
                'winbalance' => NULL,
                'winbalance_transfer' => 5.1,
                'withdraw' => NULL,
            ),
            7 => 
            array (
                'approved_by' => NULL,
                'balance' => NULL,
                'created_at' => '2024-02-14 13:24:43',
                'date' => '2024-02-14',
                'deleted_at' => NULL,
                'document' => NULL,
                'expense' => NULL,
                'id' => 8,
                'member_id' => 'M-000003',
                'payment_account' => NULL,
                'payment_type' => NULL,
                'status' => 1,
                'time' => '13:24:43',
                'transaction_id' => NULL,
                'transaction_type' => 8,
                'transfer' => NULL,
                'transfer_from' => 'M-000001',
                'transfer_to' => NULL,
                'updated_at' => '2024-02-14 13:24:43',
                'vat' => NULL,
                'winbalance' => 5.0,
                'winbalance_transfer' => NULL,
                'withdraw' => NULL,
            ),
            8 => 
            array (
                'approved_by' => NULL,
                'balance' => NULL,
                'created_at' => '2024-02-14 13:27:16',
                'date' => '2024-02-14',
                'deleted_at' => NULL,
                'document' => NULL,
                'expense' => NULL,
                'id' => 9,
                'member_id' => 'M-000001',
                'payment_account' => NULL,
                'payment_type' => NULL,
                'status' => 1,
                'time' => '13:27:16',
                'transaction_id' => NULL,
                'transaction_type' => 8,
                'transfer' => NULL,
                'transfer_from' => NULL,
                'transfer_to' => 'M-000002',
                'updated_at' => '2024-02-14 13:27:16',
                'vat' => 0.1,
                'winbalance' => NULL,
                'winbalance_transfer' => 5.1,
                'withdraw' => NULL,
            ),
            9 => 
            array (
                'approved_by' => NULL,
                'balance' => NULL,
                'created_at' => '2024-02-14 13:27:16',
                'date' => '2024-02-14',
                'deleted_at' => NULL,
                'document' => NULL,
                'expense' => NULL,
                'id' => 10,
                'member_id' => 'M-000002',
                'payment_account' => NULL,
                'payment_type' => NULL,
                'status' => 1,
                'time' => '13:27:16',
                'transaction_id' => NULL,
                'transaction_type' => 8,
                'transfer' => NULL,
                'transfer_from' => 'M-000001',
                'transfer_to' => NULL,
                'updated_at' => '2024-02-14 13:27:16',
                'vat' => NULL,
                'winbalance' => 5.0,
                'winbalance_transfer' => NULL,
                'withdraw' => NULL,
            ),
            10 => 
            array (
                'approved_by' => NULL,
                'balance' => NULL,
                'created_at' => '2024-02-15 00:57:23',
                'date' => '2024-02-15',
                'deleted_at' => NULL,
                'document' => NULL,
                'expense' => 6.0,
                'id' => 11,
                'member_id' => 'M-000001',
                'payment_account' => NULL,
                'payment_type' => NULL,
                'status' => 1,
                'time' => '12:57:23',
                'transaction_id' => NULL,
                'transaction_type' => 3,
                'transfer' => NULL,
                'transfer_from' => NULL,
                'transfer_to' => NULL,
                'updated_at' => '2024-02-15 00:57:23',
                'vat' => NULL,
                'winbalance' => NULL,
                'winbalance_transfer' => NULL,
                'withdraw' => NULL,
            ),
            11 => 
            array (
                'approved_by' => NULL,
                'balance' => NULL,
                'created_at' => '2024-02-15 00:59:10',
                'date' => '2024-02-15',
                'deleted_at' => NULL,
                'document' => NULL,
                'expense' => 10.0,
                'id' => 12,
                'member_id' => 'M-000001',
                'payment_account' => NULL,
                'payment_type' => NULL,
                'status' => 1,
                'time' => '12:59:10',
                'transaction_id' => NULL,
                'transaction_type' => 3,
                'transfer' => NULL,
                'transfer_from' => NULL,
                'transfer_to' => NULL,
                'updated_at' => '2024-02-15 00:59:10',
                'vat' => NULL,
                'winbalance' => NULL,
                'winbalance_transfer' => NULL,
                'withdraw' => NULL,
            ),
            12 => 
            array (
                'approved_by' => NULL,
                'balance' => 5.0,
                'created_at' => '2024-02-17 12:09:12',
                'date' => '2024-02-17',
                'deleted_at' => NULL,
                'document' => NULL,
                'expense' => NULL,
                'id' => 13,
                'member_id' => 'M-000001',
                'payment_account' => '01575434262',
                'payment_type' => '2',
                'status' => 0,
                'time' => '12:09:12',
                'transaction_id' => 'BX0564574848',
                'transaction_type' => 1,
                'transfer' => NULL,
                'transfer_from' => NULL,
                'transfer_to' => NULL,
                'updated_at' => '2024-02-17 12:09:12',
                'vat' => NULL,
                'winbalance' => NULL,
                'winbalance_transfer' => NULL,
                'withdraw' => NULL,
            ),
        ));
        
        
    }
}